name: Astronomer CI - Create Ephemeral Airflow

on:
  [create]

jobs:
  create-deployment:
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: extract the branch name
        id: extract_branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        shell: bash
      - name: edit deployment.yaml with feature branch name
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.deployment.configuration.name = "${{ steps.extract_branch.outputs.branch }}"' ./deployment.yaml
      - name: create deployment
        run: |
          curl -sSL https://install.astronomer.io | sudo bash -s
          astro deployment create --deployment-file ./deployment.yaml >> eph_deployment.yaml
        shell: bash


