name: Astronomer CI - Push to ephemeral deployment

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  push-deployment:
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: extract branch name
        id: extract_branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        shell: bash
      - name: get deployment id
        id: extract_dep_id
        run: |
          curl -sSL https://install.astronomer.io | sudo bash -s
          echo "dep_id=$(astro deployment inspect -n ${{ steps.extract_branch.outputs.branch }} --key metadata.deployment_id)" >>$GITHUB_OUTPUT
        shell: bash
      - name: deploy image
        run: |
          astro deploy ${{ steps.extract_dep_id.outputs.dep_id }}


